version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: standard
    versions:
    - "< 12.0.2"
    - ">= 12.0.1.a"
  - dependency-name: standard
    versions:
    - "< 12.1"
    - ">= 12.0.a"
