language: node_js

node_js:
  - "node"

cache:
  directories:
    # - "node_modules" // Because `npm ci` removes in anyways
    - "vendor"

before_install:
  - gem update --system
  - npm install -g npm@latest

before_script:
  - bundle install
  # - npm install

script:
  - bundle exec jekyll build --profile
  - npm test
  # Just testing this out.  Had some error undetected before
  - npm run build:dev
  - npm run build:prod
