language: node_js

node_js:
  - "node"

cache:
  directories:
    - "vendor"

before_install:
  - gem update --system
  - npm install -g npm@latest

before_script:
  - bundle install

script:
  - bundle exec jekyll build --profile
  - npm test
  - npm run build:dev
  - npm run build:prod
