language: node_js

node_js:
  - "node"

cache:
  directories:
    - "node_modules"
    - "vendor"

before_install:
  - gem update --system
  - npm install -g npm@latest

before_script:
  - bundle install
  - npm install

script:
  - bundle exec jekyll build --profile
  - npm test
