# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
encoding: UTF-8

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: srcery - Dark Color Scheme
author: srcery team
email: contact+site@mindtooth.no
description: >- # this means to ignore newlines until "baseurl:"
  Website for the srcery color scheme.  The site show a preview of what to expect.
baseurl: "/srcery.github.io" # the subpath of your site, e.g. /blog
url: "mindtooth.no" # the base hostname & protocol for your site, e.g. http://example.com

github: [metadata]
github:
  url:
  - https://github.com/srcery-colors


# # Social Accounts
# github_username:  MindTooth
# rss: RSS
# Social Accounts
github_username:  srcery-colors
# rss: RSS

# # Build settings
markdown: kramdown
# https://github.com/github/pages-gem/issues/482
theme: null
plugins:
  # - jekyll-feed
  - jekyll-seo-tag
  - jemoji

keep_files:
  - assets

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - src
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - public
  # - assets/images
  # - assets/js
  - webpack.config.js
  - tailwind.js
  - postcss.config.js
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
