encoding: UTF-8

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: srcery - Dark Color Scheme
author: srcery team
email: contact+site@mindtooth.no
description: >- # this means to ignore newlines until "baseurl:"
  Website for the srcery color scheme.  The site show a preview of what to expect.
baseurl: "/srcery.github.io" # the subpath of your site, e.g. /blog
url: "mindtooth.no" # the base hostname & protocol for your site, e.g. http://example.com

# github: [metadata]

# # Build settings
markdown: kramdown
# https://github.com/github/pages-gem/issues/482
theme: null
plugins:
  # - jekyll-feed
  - jekyll-seo-tag
  - jemoji

# keep_files:
#   - assets

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  # - src
  - dist
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - public
  # - assets/images
  # - assets/js
  - webpack
  - webpack.config.js
  - tailwind.js
  - postcss.config.js
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
